provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project   = var.project
      Stack     = "bootstrap"
      ManagedBy = "terraform"
    }
  }
}

data "aws_caller_identity" "current" {}

locals {
  # Bucket names are global across ALL AWS accounts, so include the account ID.
  state_bucket = "${var.project}-tfstate-${data.aws_caller_identity.current.account_id}-${var.aws_region}"
}

# S3 bucket that holds Terraform state for every other stack
resource "aws_s3_bucket" "state" {
  bucket = local.state_bucket

  # Lab setting: lets `terraform destroy` remove the bucket even if it still
  # holds state versions. In real production you'd leave this false.
  force_destroy = true
}

# Versioning = you can recover an older state file if one gets corrupted.
resource "aws_s3_bucket_versioning" "state" {
  bucket = aws_s3_bucket.state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "state" {
  bucket = aws_s3_bucket.state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

# Keep old state versions for 90 days, then expire them.
resource "aws_s3_bucket_lifecycle_configuration" "state" {
  bucket = aws_s3_bucket.state.id

  rule {
    id     = "expire-old-state-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }

  depends_on = [aws_s3_bucket_versioning.state]
}

# Refuse any request that isn't over TLS.
data "aws_iam_policy_document" "state_tls_only" {
  statement {
    sid     = "DenyInsecureTransport"
    effect  = "Deny"
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.state.arn,
      "${aws_s3_bucket.state.arn}/*",
    ]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "state" {
  bucket = aws_s3_bucket.state.id
  policy = data.aws_iam_policy_document.state_tls_only.json

  depends_on = [aws_s3_bucket_public_access_block.state]
}

# Shared partial backend config. Every other stack runs:
#   terraform init -backend-config=<path>/backend.hcl
# and only declares its own `key` in its backend "s3" block.
resource "local_file" "backend_hcl" {
  filename        = "${path.module}/../backend.hcl"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by infra/terraform/bootstrap - do not edit by hand.
    bucket       = "${aws_s3_bucket.state.bucket}"
    region       = "${var.aws_region}"
    encrypt      = true
    use_lockfile = true # S3 native locking (no DynamoDB table needed)
  EOT
}
