terraform {
  required_version = ">= 1.10"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 6.0, < 7.0"
    }
  }

  # bucket/region/locking come from ../backend.hcl (generated by the bootstrap stack):
  #   terraform init -backend-config=../backend.hcl
  backend "s3" {
    key = "eks/terraform.tfstate"
  }
}
